### PR TITLE
Comment Service CRUD

### PR DESCRIPTION
**Pull request by williamalexmorgan**
All of the CRUD functions are there except for  Update
For update I'm still thinking on how to implement this right, May ask questions about it

### CODE REVIEW

**Comment by williamalexmorgan** [comment]
All of the CRUD functions are there except for Update
--Just for Comment Service

**Review by randolphbailey — CHANGES_REQUESTED** [review]
Why do we need the entity manager?  Shouldn't we be able to use the JpaRepository interface method save() for persisting information?

**Comment by williamalexmorgan** [comment]
changed create method

**Review by randolphbailey — CHANGES_REQUESTED** [review]
A new Timestamp needs to be created at the time of insertion.  As currently written the timestamp will always have the value of whenever the spring app was started.

Also, I still feel like this is a bit overcomplicated.  I think spring is handling exceptions now?

**Review by randolphbailey — APPROVED** [review]
Eh, whatever.  We can tweak it later.

**Pull request merged**
