### PR TITLE
new controllers

### PR DESCRIPTION
**Pull request by williamalexmorgan**

### CODE REVIEW

**Comment by williamalexmorgan** [comment]
Let me know if any mistakes

**Comment by williamalexmorgan** [comment]
most of controller logic is done

**Review by randolphbailey — CHANGES_REQUESTED** [review]
Needs some changes.  Working on it

**Comment by williamalexmorgan** [comment]
Updated with PostMapping fixes

**Review by randolphbailey — APPROVED** [review]
bueno!

**Pull request merged**
